export const FORMCRASH_SELECTORS = {
  checkoutReady: 'checkout-ready',
  cart: 'cart',
  cartNext: 'cart-next',
  contactStep: 'contact-step',
  contactEmail: 'contact-email',
  contactName: 'contact-name',
  contactNext: 'contact-next',
  shippingStep: 'shipping-step',
  shippingAddressLine1: 'shipping-address-line-1',
  shippingCity: 'shipping-city',
  shippingRegion: 'shipping-region',
  shippingPostalCode: 'shipping-postal-code',
  shippingNext: 'shipping-next',
  reviewStep: 'review-step',
  submitOrder: 'submit-order',
  submissionStatus: 'submission-status',
  confirmationStep: 'confirmation-step',
  confirmationOrderId: 'confirmation-order-id',
  orderRecords: 'order-records',
  orderRecord: 'order-record',
  requestAttempts: 'request-attempts',
  requestAttempt: 'request-attempt',
  resetSample: 'reset-sample',
  modeIndicator: 'mode-indicator',
} as const;
